name: Node.js CI

on: [push]

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
      - run: echo "job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2"
    needs: job1
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job3"
    needs: [job1, job2]
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - run: echo "df"
      if: always()
      env:
        CI: true
