name: Node.js CI

on: [push]

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
     # this step generates the output variable
      name: ProduceVar  # because we're going to depend on it, we need to name the step
    - run: echo $(ProduceVar.MyVar) # this step uses the output variable
   
  job2:
    runs-on: ubuntu-latest
    dependsOn: job1
    variables:
      # map the output variable from A into this job
      varFromA: $[ dependencies.job1.outputs['ProduceVar.MyVar'] ]
    steps:
      - run: echo $(varFromA) 
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job3"
    needs: [job1, job2]
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - run: echo "df"
      if: always()
      env:
        CI: true
